[workspace]
resolver = "3"
members = ["gui", "geometry", "examples/*"]

[workspace.package]
version = "0.1.0"
authors = [""]
edition = "2024"
license = "Proprietary"
repository = ""
homepage = ""
categories = ["gui", "space"]
keywords = ["gui", "space"]
rust-version = "1.93"

[workspace.dependencies]
gui = { version = "0.1.0", path = "gui" }
geometry = { version = "0.1.0", path = "geometry" }

iced = { version = "0.14.0", default-features = true, features = ["smol"] }
env_logger = "0.11.11"
log = "0.4.33"
bytemuck = { version = "1.25.2", features = ["derive"] }
anyhow = "1.0.104"
chrono = "0.4.45"
nalgebra = "0.35.0"
image = "0.25.10"
iced_font_awesome = "0.4.4"
csv = "1.4.0"
flate2 = "1.1.9"

[workspace.lints.clippy]
large-enum-variant = "allow"