[package]
name = "gui"
description = ""
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
categories.workspace = true
keywords.workspace = true

[lints]
workspace = true

[dependencies]
geometry.workspace = true
chrono.workspace = true
ab_glyph.workspace = true

iced.workspace = true
smol.workspace = true
env_logger.workspace = true
log.workspace = true
bytemuck.workspace = true
anyhow.workspace = true
nalgebra.workspace = true
image.workspace = true
csv.workspace = true
flate2.workspace = true
iced_font_awesome.workspace = true
